server:
  port: 8887

github:
  clientId: b97d28de18ad2c43d02e
  clientSecret: 6f917f4a3b98d1ad64d69e8f70f9207064b61efe
  redirectUri: http://localhost:8887/callback
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/majiang-community?characterEncoding=utf-8&useSSL=false
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true